/** Shared shapes for the guide content manifest generated by
 *  `npm run guides:sync` (scripts/sync-guides.ts) into content/guides/. */

export interface GuideDoc {
  slug: string;
  title: string;
  /** Path relative to content/guides/ */
  file: string;
}

export interface Guide {
  slug: string;
  title: string;
  country: string;
  countryFlag: string;
  docs: GuideDoc[];
  dayTrips: GuideDoc[];
}

export interface GuideCountry {
  order: number;
  slug: string;
  name: string;
  flag: string;
  guides: Guide[];
  /** Loose country-level docs (e.g. a regional README) */
  countryDocs: GuideDoc[];
}

export interface GuideManifest {
  generatedAt: string;
  countries: GuideCountry[];
  /** Trip-wide docs (itinerario general, checklist, Eurail, presupuesto…) */
  general: GuideDoc[];
  /** Practical resources (packing list, frases, apps, documentos) */
  resources: GuideDoc[];
}
