/** Shared shapes for the guide content manifest generated by
 *  `npm run guides:sync` (scripts/sync-guides.ts) into content/guides/. */

export interface GuideDoc {
  slug: string;
  title: string;
  /** Path relative to content/guides/ */
  file: string;
}

/** A city nested inside a regional guide (Palermo inside Sicilia). Cities are
 *  navigation groups, not guides: they have no route of their own, so their
 *  doc slugs are prefixed with the city slug to stay unique inside
 *  /guias/[guide]/[doc]. */
export interface GuideCity {
  slug: string;
  title: string;
  docs: GuideDoc[];
  dayTrips: GuideDoc[];
}

export interface Guide {
  slug: string;
  title: string;
  country: string;
  countryFlag: string;
  /** Guide-level docs. On a regional guide these are the region-wide docs
   *  (transporte / gastronomía / contexto de toda la región). */
  docs: GuideDoc[];
  dayTrips: GuideDoc[];
  /** Nested city groups. Empty for the flat city guides (Roma, París…). */
  cities: GuideCity[];
}

/** Every doc reachable under /guias/[guide]/… — region-level docs and day
 *  trips plus each nested city's. Order: region docs, region day trips, then
 *  per city (docs then day trips), matching how the guide page renders. */
export function guideDocs(guide: Guide): GuideDoc[] {
  return [
    ...guide.docs,
    ...guide.dayTrips,
    ...guide.cities.flatMap((c) => [...c.docs, ...c.dayTrips]),
  ];
}

export interface GuideCountry {
  order: number;
  slug: string;
  name: string;
  flag: string;
  guides: Guide[];
  /** Loose country-level docs (e.g. a regional README) */
  countryDocs: GuideDoc[];
}

/** Deliberately no timestamp field: the output must be byte-identical when
 *  the source hasn't changed, so re-running the sync leaves git clean. */
export interface GuideManifest {
  countries: GuideCountry[];
  /** Trip-wide docs (itinerario general, checklist, Eurail, presupuesto…) */
  general: GuideDoc[];
  /** Practical resources (packing list, frases, apps, documentos) */
  resources: GuideDoc[];
}
