/** Shared shapes for the guide content manifest generated by
 *  `npm run guides:sync` (scripts/sync-guides.ts) into content/guides/. */

export interface GuideDoc {
  slug: string;
  title: string;
  /** Path relative to content/guides/ */
  file: string;
}

/** A city nested inside a regional guide (Palermo inside Sicilia). Cities are
 *  navigation groups, not guides: they have no route of their own, so their
 *  doc slugs are prefixed with the city slug to stay unique inside
 *  /guias/[guide]/[doc]. */
export interface GuideCity {
  slug: string;
  title: string;
  docs: GuideDoc[];
  dayTrips: GuideDoc[];
}

export interface Guide {
  slug: string;
  title: string;
  country: string;
  countryFlag: string;
  /** Guide-level docs. On a regional guide these are the region-wide docs
   *  (transporte / gastronomía / contexto de toda la región). */
  docs: GuideDoc[];
  dayTrips: GuideDoc[];
  /** Nested city groups. Empty for the flat city guides (Roma, París…). */
  cities: GuideCity[];
  /** Nested guides (e.g. Sicilia under Sur de Italia). Empty for leaf guides.
   *  Children keep their own `/guias/[slug]` routes; this is navigation only. */
  guides: Guide[];
  /** Parent guide slug when nested (e.g. `sur-de-italia` for `sicilia`). */
  parentSlug?: string;
}

/** Every doc reachable under /guias/[guide]/… — region-level docs and day
 *  trips plus each nested city's. Order: region docs, region day trips, then
 *  per city (docs then day trips), matching how the guide page renders.
 *  Does not walk nested child guides (those have their own routes). */
export function guideDocs(guide: Guide): GuideDoc[] {
  return [
    ...guide.docs,
    ...guide.dayTrips,
    ...guide.cities.flatMap((c) => [...c.docs, ...c.dayTrips]),
  ];
}

/** Depth-first flatten of a guide tree (container → children). Used wherever
 *  routes, search or export need every guide regardless of nesting. */
export function flattenGuides(guides: Guide[]): Guide[] {
  return guides.flatMap((g) => [g, ...flattenGuides(g.guides)]);
}

/** Doc kind behind a slug: the bare tail once the `<city>-` prefix that keeps
 *  city docs unique inside /guias/[guide]/[doc] is removed
 *  (`palermo-transporte` → `transporte`). Drives the doc icon and, in the
 *  demo, which placeholder template a doc renders. */
export function docKind(docSlug: string, cityPrefix?: string): string {
  return cityPrefix && docSlug.startsWith(`${cityPrefix}-`)
    ? docSlug.slice(cityPrefix.length + 1)
    : docSlug;
}

/** Katia's raw research notes, pasted from her own doc rather than curated
 *  into the standard files. They belong to the guide, so they read fine on
 *  /guias — but they are not one of the seven canonical docs: they never get a
 *  chip on a stop card, and the demo drops them instead of faking one. */
export function isNotasKatia(docSlug: string, cityPrefix?: string): boolean {
  return docKind(docSlug, cityPrefix) === "notas-katia";
}

export interface GuideCountry {
  order: number;
  slug: string;
  name: string;
  flag: string;
  guides: Guide[];
  /** Loose country-level docs (e.g. a regional README) */
  countryDocs: GuideDoc[];
}

/** Deliberately no timestamp field: the output must be byte-identical when
 *  the source hasn't changed, so re-running the sync leaves git clean. */
export interface GuideManifest {
  countries: GuideCountry[];
  /** Trip-wide docs (Eurail, presupuesto) — allowlist in `sync-guides.ts` */
  general: GuideDoc[];
  /** Practical resources (packing list, frases, apps, documentos) */
  resources: GuideDoc[];
}
